blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/elelabdev/microsoft-azure-cidr-analyzer/discussions/categories/q-a
    about: Please use GitHub Discussions for questions.
