name: "Feature request"
description: Suggest an idea for Microsoft Azure CIDR Analyzer
labels: [enhancement]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? Tell us what would make the extension more useful.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What should happen? Include sketches or screenshots if helpful.
      validations:
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context or information about the feature request here.
